### ISSUE TITLE
'TypeError: must be real number, not NoneType' when using h3_pyspark

### ISSUE THREAD

**Issue by Tingmi** [kevinschaich/h3-pyspark#4]
Hi, I have the following spark dataframe and the column of h3 indices is created by applying the lat, lng pairs and the resolution to h3_pypark.geo_to_h3(lat, lng, resolution) function. However I encountered the following error when I tried to check if there's any null in the index column. And it's not only isNull() not working but also any other subsetting operations which all throw me the same error, could anyone provide some insights on what might be the issue and how to fix it? Thanks in advance!

**dataframe**:
![image](https://user-images.githubusercontent.com/93330035/154133915-2b01fcbd-19fe-401a-b128-4e18e9797a7e.png)

**errors**: 
![image](https://user-images.githubusercontent.com/93330035/154134325-48b2cc28-02a4-4eda-ab6f-971bfe7a22a5.png)

**Comment by kevinschaich** [comment]
Hey @Tingmi , I think Databricks is likely sampling your dataframe to give you a real time preview in your initial call and it just so happens that it didn't encounter any null rows in the sample.

I expect the error is that one of your lat/long columns contains a null value (that's the error – it wants a number and not a null value). I'd suggest filtering to null lat/longs and call `df.show()` to see if there are any?

**Comment by Tingmi** [comment]
Hi@[kevinschaich](https://github.com/kevinschaich), thanks for getting back to me so quickly. I checked the lat/lng to see if there's any nulls, but it turns out there's not, please see below:

![image](https://user-images.githubusercontent.com/93330035/154189416-cff169b8-7018-40fa-8116-6cadbb6c2c1c.png)

![image](https://user-images.githubusercontent.com/93330035/154189449-d4c66ac2-a407-44bd-80fd-0ad91e87a496.png)

And I also went ahead doing the following with na.drop just in case I didn't do it correctly above and got the dataframe:

![image](https://user-images.githubusercontent.com/93330035/154189963-0decd39f-e0b6-4a43-8e09-cc5dd1509acb.png)

However I still got the same error as before:
![image](https://user-images.githubusercontent.com/93330035/154189692-3b6863b4-e7ee-4667-af99-685aa7521f50.png)

Is there anything else I should try? Thanks!!!

**Comment by kevinschaich** [comment]
@Tingmi nothing is sticking out off the top of my head. How large is your source dataset? Is it sensitive / would you be able to share it here?

**Comment by Tingmi** [comment]
@kevinschaich our problem got resolved without any code change. Not sure what happened, but maybe it's something due to spark?

**Comment by kevinschaich** [comment]
Yeah I'd say Spark or Databricks env possibly @Tingmi ? Hard to say if it's not consistent. 

Anyway thanks for filing, I'll close this one out for now.
